-- Create new table RECENT_SEARCHES with ID, CREATED_DATE, CREATED_BY, CUSTOMER_ID, USER_ID, SEARCH_KEY, QUERY

CREATE TABLE SEARCH_HISTORY (
    ID                          NUMBER(38,0) NOT NULL,
    UUID 						VARCHAR2(36 BYTE) NOT NULL,
    CREATED_DATE                DATE NOT NULL,
    CREATED_BY                  NUMBER(38,0) NOT NULL,
    CUSTOMER_ID                 NUMBER(38,0) NOT NULL,
    SEARCH_KEY                  VARCHAR2(256 CHAR) NOT NULL,
    QUERY                       CLOB NOT NULL
);

ALTER TABLE SEARCH_HISTORY ADD CONSTRAINT SEARCH_HISTORY_PK PRIMARY KEY (ID) NOVALIDATE;
ALTER TABLE SEARCH_HISTORY ADD CONSTRAINT SEARCH_HISTORY_CUST_ID_FK01 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID) ON DELETE CASCADE ENABLE NOVALIDATE;
ALTER TABLE SEARCH_HISTORY ADD CONSTRAINT SEARCH_HISTORY_USER_ID_FK02 FOREIGN KEY (USER_ID) REFERENCES USER_LOCAL (ID) ON DELETE SET NULL
ALTER TABLE SEARCH_HISTORY ADD CONSTRAINT SEARCH_HISTORY_CREATED_BY_FK03 FOREIGN KEY (CREATED_BY) REFERENCES USER_SNAPSHOT (ID) ON DELETE SET NULL ENABLE NOVALIDATE;

CREATE INDEX SEARCH_HISTORY_IX01 ON SEARCH_HISTORY (CUSTOMER_ID);
CREATE INDEX SEARCH_HISTORY_IX02 ON SEARCH_HISTORY (USER_ID);
CREATE INDEX SEARCH_HISTORY_IX03 ON SEARCH_HISTORY (CREATED_BY);

CREATE SEQUENCE ID_SEARCH_HISTORY
INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1001 CACHE 20 NOCYCLE NOORDER;